collections:
  - name: blog
    label: Actualités
    folder: src/content/blog
    create: true
    extension: md
    fields:
      - name: title
        label: Title
        type: text

      - name: pubDatetime
        label: Publication date
        type: date
        default: 2026-01-03

      - name: description
        label: Description
        type: textarea

      - name: body
        label: Content
        type: rich-text

      - name: image
        label: Featured Image
        type: image